### ISSUE TITLE
keepalive is being sent on a disconnected socket

### ISSUE THREAD

**Issue by gmelika** [coinbase/gdax-node#105]
```
err /app/node_modules/gdax/node_modules/ws/lib/WebSocket.js:160
err     throw new Error('not opened');
err     ^
err 
Error Error: not opened
err     at WebSocket.ping (/app/node_modules/gdax/node_modules/ws/lib/WebSocket.js:160:11)
err     at null._repeat (/app/node_modules/gdax/lib/clients/websocket.js:77:19)
err     at wrapper [as _onTimeout] (timers.js:279:11)
err     at Timer.listOnTimeout (timers.js:92:15)
```

this is using 0.4.2, and looks like the following is the culprit:

https://github.com/coinbase/gdax-node/blob/98d044efba8329e0fd4f583ae2efaaf60ac81d8c/lib/clients/websocket.js#L76-L78

**Comment by fb55** [comment]
Fixed in #150
