### ISSUE TITLE
0.5.0  es6 problems

### ISSUE THREAD

**Issue by MMrj9** [coinbase/gdax-node#184]
After upgrading to v 0.5.0 I'm getting this errors:

```
const { Readable } = require('stream');
      ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/mmrj9/Documents/Projects/trading/node_modules/gdax/index.js:2:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

```

**Comment by rmm5t** [comment]
What version of node are you running? It doesn't sound like you have Node v6+ in your runtime.

[gdax requires at least node v6](https://github.com/coinbase/gdax-node/blob/master/package.json#L42)
