### ISSUE TITLE
Errors when placing buy or sell orders

### ISSUE THREAD

**Issue by wahnker** [coinbase/gdax-node#202]
Code:
```
async function placeBuyOrder() {
   var buyPrice = roundDollars(ticker.price * (1-MARGIN));
   buyPrice = Math.min(buyPrice, ticker.best_bid);

   buyParams = {
      'price': buyPrice, // USD
      'size': MIN_ORDER_SIZE,  // BTC
      'product_id': PRODUCT,
   };

   try {
      orderData = await authedClient.buy(buyParams);
   } catch(error) {
      ....
   }
```

And here's the error I'm getting.  It happens for both buy and sell orders.  I think the orders actually go through, but since I can't get the ID, my code gets out of sync.

```
 { Error: Response could not be parsed as JSON
    at Request._callback (/Users/___/Code/trading/node_modules/gdax/lib/clients/public.js:70:15)
    at Request.self.callback (/Users/___/Code/trading/node_modules/request/request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/___/Code/trading/node_modules/request/request.js:1171:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/___/Code/trading/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

**Comment by rmm5t** [comment]
You haven't pasted enough code to fully debug, but one thing I see off the bat is that `price` and `size` are supposed to be passed as strings, not numbers. 

Also, please make sure that you're using the latest version from the `master` branch (for `Promise` support). See #148 for more information about that:

```
npm install coinbase/gdax-node
```

**Comment by fb55** [comment]
Thanks @rmm5t!
