### ISSUE TITLE
"callback is not a function" when specifying pagination

### ISSUE THREAD

**Issue by AddisonBurn** [coinbase/gdax-node#224]
I am extremely new to JavaScript so this is really a question for a forum but I don't know if one exists for this library.

When trying to use the functions with additional parameters like pagination or level as seen below:

```
const Gdax = require('gdax');
const publicClient = new Gdax.PublicClient();

publicClient.getProductOrderBook('ETH-USD', { level: 3 }, (error, response, book) => { 
	console.log(book.length);
 });
```

I get the following error:
(I have shortened the file paths for visual)

```
/node_modules/gdax/lib/clients/public.js:45
      callback(err, response, data);
      ^

TypeError: callback is not a function
    at Request._callback (/node_modules/gdax/lib/clients/public.js:45:7)
    at Request.self.callback (/node_modules/request/request.js:187:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (node_modules/request/request.js:1044:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/node_modules/request/request.js:965:12)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
```

I suspect this is a problem with the library but it could very easily be something I am doing incorrectly.

**Comment by AddisonBurn** [comment]
Nevermind, after reading through other issues here I realized I was not on the current Github version.
Updated and it works well now.
