### ISSUE TITLE
OrderbookSync fails on startup

### ISSUE THREAD

**Issue by proever** [coinbase/gdax-node#26]
Hi there,

I'm getting an error that I don't think is just me with OrderbookSync: it throws an error when it's initialized, saying "TypeError: self.connect is not a function"

`
at Object.WebsocketClient (/node_modules/gdax/lib/clients/websocket.js:22:8)
`
`
at Object.OrderbookSync (/node_modules/gdax/lib/orderbook_sync.js:22:19)
`

**Comment by proever** [comment]
Sorry, I'm new to Javascript and was forgetting the new keyword before calling Gdax.OrderbookSync()
