### ISSUE TITLE
OrderbookSync RangeError

### ISSUE THREAD

**Issue by johnjelinek** [coinbase/gdax-node#3]
code:

```
var Gdax = require('gdax');
var orderbookSync = new Gdax.OrderbookSync('ETH-USD')
```

then just wait a little and ...

```
RangeError: out of range index
    at RangeError (native)
    at fastCopy (/mnt/c/Users/John Jelinek/Documents/gdax/node_modules/ws/lib/Receiver.js:382:24)
    at Receiver.add (/mnt/c/Users/John Jelinek/Documents/gdax/node_modules/ws/lib/Receiver.js:82:3)
    at TLSSocket.firstHandler (/mnt/c/Users/John Jelinek/Documents/gdax/node_modules/ws/lib/WebSocket.js:775:22)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at TLSSocket.Readable.push (_stream_readable.js:135:10)
    at TLSWrap.onread (net.js:542:20)
```

**Comment by johnjelinek** [comment]
oh -- also, I'm running this in a node repl

**Comment by chrisinajar** [comment]
This happens in node version 6.3+ (tested from 6.3.0 up till 6.7.0)... Installing either node 6.2, or the LTS 4.x series, will resolve the issue. You can use [nvm](https://github.com/creationix/nvm) or the more simple but more aggressive [n](https://github.com/tj/n).

If you install from the repository it will work, the package.json in the repo points at `ws` version 1.1.1 which no longer has this issue. Once the author publishes to npm this wont be a problem anymore.

**Comment by loriopatrick** [comment]
Resolved
