### ISSUE TITLE
Invalid API Key

### ISSUE THREAD

**Issue by toymachiner62** [coinbase/gdax-node#340]
I just created an API key on coinbase pro and i'm trying to make simple calls against coinbase pro's sandbox and I keep getting a 400 with "invalid API Key"

Should the key I create on coinbase pro also work against the sandbox api?

Can you provide anymore debug info as to why my key is invalid?

I'm using version 0.8.0 of gdax-node
```
'use strict'

const Gdax = require('gdax');
const api = 'https://api.pro.coinbase.com'
const sandbox = 'https://api-public.sandbox.pro.coinbase.com'
const KEY = process.env.coinbase_key
const SECRET = process.env.coinbase_secret
const PASSPHRASE = process.env.coinbase_passphrase
// const publicClient = new Gdax.PublicClient()
console.log('key = ', KEY)
console.log('secret = ', SECRET)
console.log('passphrase = ', PASSPHRASE)
const client = new Gdax.AuthenticatedClient(KEY, SECRET, PASSPHRASE, sandbox) // TODO Change this to run against prod

setInterval(start, 1000)

function start () {
  getTickerBook()
  getCoinbaseAccounts()
}

/**
 * Gets book info for ETC-USD
 * @return {Promise} [description]
 */
function getTickerBook () {
  client.getProductTicker('ETC-USD')
    .then(results => {
      console.log('results = ', results)
    })
    .catch(err => {
      console.log('err = ', err)
    })
}

function getCoinbaseAccounts () {
  client.getCoinbaseAccounts()
    .then(results => {
      console.log('coinbase accounts = ', results)
    })
    .catch(err => {
      console.log('err = ', err)
    })
}
```

Error:
```
 { Error: HTTP 400 Error: Invalid API Key
    at Request._callback (/Users/tomcaflisch/Sites/crypto-algorithm/node_modules/gdax/lib/clients/public.js:68:15)
    at Request.self.callback (/Users/tomcaflisch/Sites/crypto-algorithm/node_modules/request/request.js:185:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/Users/tomcaflisch/Sites/crypto-algorithm/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/Users/tomcaflisch/Sites/crypto-algorithm/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
...
```

**Comment by toymachiner62** [comment]
I found in the docs where it mentions that I need to create a sandbox api key for the sandbox explicitly
