### ISSUE TITLE
HTTP 400 Error: Invalid client_oid

### ISSUE THREAD

**Issue by vansergen** [coinbase/gdax-node#345]
I tried to assign different values to `client_oid` but every time I receive this error:

> Error: HTTP 400 Error: Invalid client_oid
    at Request._callback (/home/user333/test/node_modules/gdax/lib/clients/public.js:68:15)
    at Request.self.callback (/home/user333/test/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/home/user333/test/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/home/user333/test/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Could `client_oid` be any string? For example, `client_oid = '123'`

**Comment by mjmau** [comment]
> Could client_oid be any string? For example, client_oid = '123'

No, it has to be in the exact format of a UUID, such as: 1822e338-8e16-b740-e998-fcc33dcfc443

**Comment by fb55** [comment]
Thanks @mjmau!
