### ISSUE TITLE
OrderbookSync Assertion Error: `order.id` and `match.maker_order_id` not equal

### ISSUE THREAD

**Issue by mjesuele** [coinbase/gdax-node#48]
Hey hey. I'm using OrderbookSync and in the latest code from `master` I'm getting this error shortly after the websocket connects (leaving some of my logging in here for context):

```
Opening connection and loading order book...
Book loaded.
Best Ask: 173.99 ⬇︎
Best Bid: 173.98 ⬇︎

Book loaded.

/Users/matt/dev/arby/node_modules/gdax/lib/orderbook.js:137
    assert.equal(order.id, match.maker_order_id);
           ^
AssertionError: 'c4e57d1d-7cd5-4286-bac3-11ee67fe7618' == '5f2367bb-070e-4838-bbcc-b163ff4e127e'
    at Orderbook.prototype.match (/Users/matt/dev/arby/node_modules/gdax/lib/orderbook.js:137:12)
    at OrderbookSync.prototype.processMessage (/Users/matt/dev/arby/node_modules/gdax/lib/orderbook_sync.js:128:14)
    at OrderbookSync.prototype.onMessage (/Users/matt/dev/arby/node_modules/gdax/lib/orderbook_sync.js:51:12)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:194:7)
    at Receiver._receiver.onmessage (/Users/matt/dev/arby/node_modules/gdax/node_modules/ws/lib/WebSocket.js:146:54)
    at Receiver.dataMessage (/Users/matt/dev/arby/node_modules/gdax/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/Users/matt/dev/arby/node_modules/gdax/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/Users/matt/dev/arby/node_modules/gdax/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/Users/matt/dev/arby/node_modules/gdax/node_modules/ws/lib/Receiver.js:139:10)
    at TLSSocket._ultron.on (/Users/matt/dev/arby/node_modules/gdax/node_modules/ws/lib/WebSocket.js:142:22)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at TLSSocket.Readable.push (_stream_readable.js:136:10)
    at TLSWrap.onread (net.js:560:20)
```

Any help would be appreciated. Thanks!

**Comment by kenfehling** [comment]
I believe this PR should fix this issue: https://github.com/coinbase/gdax-node/pull/53

**Comment by kenfehling** [comment]
I believe this PR should fix the issue: https://github.com/coinbase/gdax-node/pull/54

**Comment by fb55** [comment]
Looks like it, thanks for the note!
