### ISSUE TITLE
TypeError: Cannot read property 'isValidUTF8' of undefined (Websocket)

### ISSUE THREAD

**Issue by marciomansur** [coinbase/gdax-node#74]
Hi, I'm creating a very simple socket client to listen to Gdax server, but I always get this problem.

The code:

``` javascript
import request from 'request-promise';
import config from 'config';
import Gdax from 'gdax';

// get all assets pairs
const opts = {
  url: `${config.exchanges.gdax.api}/products`,
  headers: {
    'User-Agent': 'myapp'
  },
  json: true
};

request(opts)
  .then(data => data.map(d => d.id))
  .then((assets) => {
    const websocket = new Gdax.WebsocketClient(assets);
    websocket.on('message', (data) => {
      console.log(data);
    });
  })
  .catch((err) => {
    console.log(err.message);
  });
```

The error:

```
/Projects/exchanges/node_modules/gdax/node_modules/ws/lib/Receiver.js:532
            if (!Validation.isValidUTF8(messageBuffer)) {
                           ^

TypeError: Cannot read property 'isValidUTF8' of undefined
    at Projects/exchanges/node_modules/gdax/node_modules/ws/lib/Receiver.js:532:28
    at Receiver.applyExtensions (Projects/exchanges/node_modules/gdax/node_modules/ws/lib/Receiver.js:371:5)
    at Projects/exchanges/node_modules/gdax/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (Projects/exchanges/node_modules/gdax/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.finish (Projects/exchanges/node_modules/gdax/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (Projects/exchanges/node_modules/gdax/node_modules/ws/lib/Receiver.js:499:31)
    at Receiver.add (Projects/exchanges/node_modules/gdax/node_modules/ws/lib/Receiver.js:103:24)
    at TLSSocket.realHandler (Projects/exchanges/node_modules/gdax/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at TLSSocket.Readable.push (_stream_readable.js:136:10)
    at TLSWrap.onread (net.js:561:20)
[nodemon] app crashed - waiting for file changes before starting...
```

After some searching, some people with the same issue said is something about the `ws` module version and is incompatibility with `utf-8-validate`. I've tried everything with every version and nothing. 

Thank you!

**Comment by awitherow** [comment]
What version of the ws module do you have installed in your node modules? Can you check the package.json of the `/Projects/exchanges/node_modules/gdax/node_modules/ws/` directory?

**Comment by marciomansur** [comment]
I have in my node_modules the version `^3.0.0`. On `/Projects/exchanges/node_modules/gdax/node_modules/ws/` package.json is `1.1.1`. Is the new version with the latest version?

**Comment by awitherow** [comment]
There has been an upgrade I believe, try upgrading your gdax node package to latest and see if it is working 👍

**Comment by marciomansur** [comment]
I'll try to use github's version then, because the last available version on npm is `0.4.2` (which has the ws `1.1.1` version)

**Comment by marciomansur** [comment]
The `ws` newest version is working. Thanks @awitherow ! I'll close the issue

**Comment by awitherow** [comment]
🎉

**Comment by awitherow** [comment]
@fb55 would be good to have some release notes on this?
