### ISSUE TITLE
Error: socket hang up 

### ISSUE THREAD

**Issue by Raukk** [coinbase/gdax-node#97]
I just recently started getting this, and I'm not sure what is causing it or how to handle it. 
Do you know what is causing it o what the fix would be? 

{ Error: socket hang up 
    at TLSSocket.onHangUp (_tls_wrap.js:1124:19) 
    at TLSSocket.g (events.js:291:16) 
    at emitNone (events.js:91:20) 
    at TLSSocket.emit (events.js:185:7) 
    at endReadableNT (_stream_readable.js:974:12) 
    at _combinedTickCallback (internal/process/next_tick.js:80:11) 
    at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET' }

**Comment by fb55** [comment]
That error in general means that the connection was dropped by one of the sides. That occasionally happens on our end (our load balancing isn't ideal at the moment), but if it is happening a lot please verify that your network connection is stable. If you can't figure it out try to reconnect and pause placing orders (if you're running a bot) in the meantime.
